language: node_js
node_js:
- '8'

env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
branches:
  only:
  - develop
  - release
  - master

install:
- yarn

script:
- bash .travis/build.sh

deploy:
  provider: script
  script: bash .travis/deploy.sh
  skip_cleanup: true
  on: 
    all_branches: true